### ISSUE TITLE
Build but won't run in simulator

### ISSUE THREAD

**Issue by tomjuszczyk** [api-ai/api-ai-ios-sdk#1]
I'm getting this project to build successfully but the simulator doesn't seem to want to open and it's not recognizing my iPhone 5s as a device, are there special requirements or limitations I should be aware of in general?

**Comment by sstepashka** [comment]
Hi,

Which iOS-version on your device?
Do you run demo application or another?

**Comment by sstepashka** [comment]
and XCode version?

**Comment by tommybananas** [comment]
8.3 but the simulator isn't launching either

**Comment by tommybananas** [comment]
xcode 6.3 (6D570)

**Comment by artemgoncharuk** [comment]
Hey Tommy, Could you please post the error details here?
We do not have any specific requirements - should run on 5s and your setup without problems.
