### ISSUE TITLE
actionIncomplete not part of result.

### ISSUE THREAD

**Issue by chirag04** [api-ai/api-ai-ios-sdk#12]
Refer: https://docs.api.ai/v18/docs/query#post-query

**Comment by paulwalczewskiLeotech** [comment]
+1

**Comment by mark-holland-leotech** [comment]
Apparently this is a server issue. textRequest seems to have the field for me but not with voiceRequest.

**Comment by sstepashka** [comment]
I think it task about mapping to objc class :)
