### ISSUE TITLE
Add Note in Readme about RecognitionEngine

### ISSUE THREAD

**Issue by cancan101** [api-ai/api-ai-ios-sdk#14]
The Android SDK says:

> Currently, speech recognition is performed using Google's Android SDK, either on the client device or in the cloud. Recognized text is passed to the API.AI through HTTP requests. Also you can try Speaktoit recognition engine (Use AIConfiguration.RecognitionEngine.Speaktoit).

however there is no similar note for the iOS SDK. What is the engine used on iOS? Is it Speaktoit?

**Comment by sstepashka** [comment]
Yes, Currently iOS SDK uses only our speech recognition.
