### ISSUE TITLE
Pulse animation issue while recording voice

### ISSUE THREAD

**Issue by Garry9915** [api-ai/api-ai-ios-sdk#16]
In demo app(iOS), I can see the pulse animation effect(In Voice Button Request screen see the effect around microphone image) but same I have implemented in my app but unable to get same effect. Can you please help me to sort the same. Also couple of times getting request time out issue.

**Comment by sstepashka** [comment]
You can see code https://github.com/api-ai/api-ai-ios-sdk/blob/master/ApiAI/UIKit/Private/AIVoiceLevelView.m
