### ISSUE TITLE
Can I get user's recorded voice from API.AI SDK?  I need to send it to my server for user's voice verification.

### ISSUE THREAD

**Issue by ivish** [api-ai/api-ai-ios-sdk#18]

**Comment by almasry** [comment]
@ivish where you able to find an answer to this question or find alternative solutions ? I'm looking for something similar

**Comment by ivish** [comment]
@almasry I don't think that API.AI SDK provides access to the recording.. You have to depend on your device to record user's voice & then stream it to API.AI
