### ISSUE TITLE
Can't build ApiAIDemo

### ISSUE THREAD

**Issue by OlexandrStepanov** [api-ai/api-ai-ios-sdk#2]
Hello.

I have followed to instructions in README, and have run "pod update"In the folder, but XCode fails to compile with error
*"unknown type name 'AIResponse'"*.
I see that the reason is, that *AIResponse.h* file simply is not included in *ApiAI.h*, namely it's wrapped with *#if __has_include("AIResponse.h")* , which is false, for some reason.
Could you, please, clarify this situation, and why import of this header is wrapped with this if, what is the purpose?

**Comment by sstepashka** [comment]
Requeired 

XCode version
Cocoapods version

https://github.com/api-ai/api-ai-ios-sdk/tree/master/ApiAIDemo

This is Demo, isn't it?
Do you make any changes of project or Podfile?

**Comment by OlexandrStepanov** [comment]
@sstepashka ,
XCode: 7.0.1
Cocoapods: 0.39.0.beta.3
Yes, we are talking about ApiAIDemo on Objective-C.
The only changes I've made to project: 
 * provided clientAccessToken and subscriptionKey in AppDelegate.m
 * changed clientAccessToken and subscriptionKey in ViewController.m. Note, there are currently some exact tokens instead of placeholders in master branch.
 * Changed app bundle ID and team to resolve provisioning issues to run on device, because as far as I understand, audio session will work only on device.

No changes to the Podfile.

**Comment by sstepashka** [comment]
Thanks for Your message. Library was updated in cocoapods.

**Comment by OlexandrStepanov** [comment]
@sstepashka ,
Thanks for fix. Problem with AIResponse is gone after your commit, however I still had some compiler errors:
* 'ApiAI/UIKit/AIVoiceRequestButton.h' file not found
#import <ApiAI/UIKit/AIVoiceRequestButton.h>*
I fixed that by changing to
*#import <AIVoiceRequestButton.h>*

Also, I was forced to disable bitcode due to linker error:
*ld: -weak_library and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)*

After these changes, app was built fine.
