### ISSUE TITLE
Voice recognition in iOS 

### ISSUE THREAD

**Issue by ernadeem** [api-ai/api-ai-ios-sdk#26]
Hi All,

There is no tutorial and way how to use voice to text conversion using api.ai in iOS . In sample app its showing only text speech not voice. Please let me know if this sdk support voice to text and how to enable it?

**Comment by sstepashka** [comment]
Voice Recognition has been removed from SDK. Now you can use only third-party libraries for voice recognition and send to api.ai recognised text. So, You can also using iOS voice recognition.
