### ISSUE TITLE
Recommended approach for always listening?

### ISSUE THREAD

**Issue by rajohns08** [api-ai/api-ai-ios-sdk#3]
Could you guys document the recommended approach of how to use this SDK for an always listening type of scenario. Where requests are periodically sent up silently in background.

**Comment by sstepashka** [comment]
Hi,
Can you detail describe scenario?

**Comment by artemgoncharuk** [comment]
We currently do not support always listening via the SDK.
One approach would be to use a third-party trigger word solution (similar to Hey Siri / OK Google).
