### ISSUE TITLE
iOS SDK voice recognition not recognizing returning desired result

### ISSUE THREAD

**Issue by dhirenipatel** [api-ai/api-ai-ios-sdk#5]
Using iOS SDK voice recognition is not working properly. For Android it's working properly. Also whenever I speak using iOS SDK all requests are visible as Sub-Log of main Log. Is that a issue or do I need to set some parameter in the iOS sdk provided?

**Comment by sstepashka** [comment]
Hi, do your have some error? You use demo application or not?

**Comment by dhirenipatel** [comment]
Nope. There is no error. It's not recognizing properly. I am speaking same sentence simultaneous on my android and iOS app. Android app is doing very good while iOS app is not recognizing. I can share my client access token if required. I am using api.ai with email id normjr1@gmail.com. I can see in api.ai log that my recognized sentenced is totally wrong.

**Comment by sstepashka** [comment]
Maybe... You can show Your code? Android SDK using google speech recognizer, but in iOS using our ASR... it differed

**Comment by sstepashka** [comment]
Or just low quality of the recognition?

**Comment by dhirenipatel** [comment]
Here it goes

-(instancetype)initWithView:(UIView*)view{
    self.apiAI = [ApiAI sharedApiAI];
    
    // Define API.AI configuration here.
    id <AIConfiguration> configuration = [[AIDefaultConfiguration alloc] init];
    configuration.baseURL = [NSURL URLWithString:@"https://api.api.ai/v1"];
    configuration.clientAccessToken = @"XXXXX"; 
    configuration.subscriptionKey = @"YYYY";
    self.apiAI.configuration = configuration;
    self.view = view;
    
    return self;
}
-(UIView*)getRequestButtonView:(BOOL)showButton{
    if (showButton) {
        UIView *customView = [[UIView alloc] init];
        [customView setFrame:CGRectMake(20, self.view.frame.size.height/4, self.view.frame.size.width - 40, self.view.frame.size.height/3 + 50)];
        customView.layer.cornerRadius = 10;
        UILabel *speakLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, 15, customView.frame.size.width, 30)];
        [speakLabel setTextAlignment:NSTextAlignmentCenter];
        speakLabel.text = @"Speak";
        [speakLabel setTextColor:[UIColor darkGrayColor]];
        [customView addSubview:speakLabel];
        [customView setBackgroundColor:[UIColor colorWithWhite:200.0/255 alpha:1.0]];
        AIVoiceRequestButton *button = [[AIVoiceRequestButton alloc] init];
        [button setSuccessCallback:^(id response) {
            NSLog(@"Response: %@",[response description]);
        }];
        
        [button setFailureCallback:^(NSError *error) {
            NSLog(@"Error: %@",[error description]);
        }];
        
        [customView addSubview:button];
        [self alignToCenter:button toView:customView];
        
        self.requestButton = button;
        return customView;
    }
    return nil;
}

**Comment by sstepashka** [comment]
You skip step "Init audio session.". If does not do it, then audio cannot be recorded.

see https://github.com/api-ai/api-ai-ios-sdk#integratingintoyourapp

That's right?

**Comment by dhirenipatel** [comment]
It has been done in AppDelegate.m

	-(void)initAudioService{
	   [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];
	   [[AVAudioSession sharedInstance] setActive:YES error:nil];
	}

**Comment by dhirenipatel** [comment]
True, it is a low quality of recognition. Some simple text it's able to recognize.

**Comment by sstepashka** [comment]
Okey. I Cannot fix this problem now. We always working with quality of out ASR.
