### ISSUE TITLE
iOS Demo application is giving error "Could not recognize the text from the voice data" everytime

### ISSUE THREAD

**Issue by IamProgrammer** [api-ai/api-ai-ios-sdk#6]
Hi.

I have two questions here for API-AI iOS demo application.

1) Regarding compilation issue : 
I downloaded the iOS API-AI sdk from github and updated to 0.4.6 using (pod update). I faced a compilation error "- (AIVoiceRequest *)voiceRequest" as not declared 
due to the value of flag "AI_SUPPORT_VOICE_REQUEST" is 0. I fixed it by changing the flag to 1 and compiled it.  

Does it mean, the API-AI iOS SDK is not supporting voice requests in this release ?

2) Regarding recognition results:

 After running the demo, for "Simple Voice request" , everytime getting response "Could not recognise the text from the voice data". 

Please let me know, what is the quality of iOS ASR for API-AI.

Response as below:

{
    id = "9bffc17a-b717-4d49-8afa-003bce8d3054";
    status =     {
        code = 400;
        errorDetails = "Could not recognize the text from the voice data.";
        errorType = "bad_request";
    };
    timestamp = "2015-12-09T06:37:22.128Z";
}

**Comment by sstepashka** [comment]
@IamProgrammer Hi,
1) I have some question... Which version of XCode?
2) This is mean ASR (sound recogniser) cannot recognize text from audio data. We now work for fix than, should be rocognized empty text without error.

**Comment by IamProgrammer** [comment]
1) I am using XCode 6.4 version and iOS 8.4.
2) I did not understand what were you saying regarding ASR.

**Comment by sstepashka** [comment]
@IamProgrammer ,

1) Current version library support voice request, but have some problems with XCode older &.x. I'm try to fix it today or tomorrow.
2) "Could not recognize the text from the voice data." - It means that no voice in audio stream(audio data). Or... Server cannot recognize voice in audio stream(audio data).

**Comment by IamProgrammer** [comment]
@sstepashka :  Any update on above issue.

**Comment by sstepashka** [comment]
Does you still have this troubles? All of this should be resolved in latest version of library. Update it.
