### ISSUE TITLE
It doesn't recognize Spanish language

### ISSUE THREAD

**Issue by JosepEscobar** [api-ai/api-ai-ios-sdk#7]
I have configured the agent in Spanish but it almost doesn't recognize any word. Such as "ordenador", it recognizes it as "open alarm".

**Comment by sstepashka** [comment]
Hi,

Change language for request (lang property, default value equal 'en') or set property in ApiAI class, It language will be used all requests.

**Comment by JosepEscobar** [comment]
Wow! I fixed! :D 
.h
 @property(nonatomic, strong) ApiAI *openAPI;

.m
 _openAPI = [[ApiAI alloc] init];
 _openAPI.lang = @"es";

thanks!

**Comment by sstepashka** [comment]
No problem!
