### ISSUE TITLE
I need to save the audio in an archive inside the documents folder

### ISSUE THREAD

**Issue by JosepEscobar** [api-ai/api-ai-ios-sdk#8]
how can I save the audio with AVAudioRecorder or other, before or after recognizing it?

**Comment by JosepEscobar** [comment]
I managed to do it! 
_recorder = [[VoiceRecorder alloc] init];
    if([_recorder startAudioSession]){
        NSString *mail = [[NSUserDefaults standardUserDefaults] objectForKey:@"email"];
        filePath = [[NSString alloc] initWithString: [docsDir stringByAppendingPathComponent:@"carrete/"]];
        filePath = [[NSString alloc] initWithString: [filePath stringByAppendingString:_photo.voiceFile]];
        [_recorder recordToFile:filePath];
}

**Comment by sstepashka** [comment]
What reason for use it? 

Our SDK doesnt support save audio file, but It can be implemented if required. Now you cannot legal save audio to file, that sended to server.

**Comment by JosepEscobar** [comment]
I need record for my app funcitionality. Educational propose only.
