### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by raineroviir** [api-ai/api-ai-ios-sdk#9]
I'm trying out the demo app and voice requests return unauthorized.  I inserted the sub key and client token into viewcontroller.m.

**Comment by sstepashka** [comment]
Hi,

Can your send me your keys, or better code with setup it like following: 

`configuration.clientAccessToken = @"YOUR_CLIENT_ACCESS_TOKEN";`
`configuration.subscriptionKey = @"YOUR_SUBSCRIPTION_KEY";`

**Comment by raineroviir** [comment]
```
configuration.clientAccessToken = @"2cd61ebff024440a950b51a50f0446a8";
configuration.subscriptionKey = @"d5ccd105-80b0-4242-9328-82a996624c72";
```

**Comment by sstepashka** [comment]
Hm... Your keys right and work.

I think you should change this keys in AppDelegate.m file for right work.

File "ViewController.m" contains older and unused code. I'm will remove it or refactor for using in examples.

Thank you.

**Comment by raineroviir** [comment]
Working! Thank you.
